# These are supported funding model platforms

github: mawaba
patreon: mawaba
open_collective: mawaba
ko_fi: mawaba
buy_me_a_coffee: mawaba
custom: ['https://github.com/sponsors/mawaba', 'https://mawaba.org/sponsor']
